### ISSUE TITLE
MQTT subscriber fails to connect to broker

### ISSUE THREAD

**Issue by sebplorenz** [micronaut-projects/micronaut-mqtt#70]
I have the problem that my Micronaut mqtt client does not subscribe to the server. The strange thing is that this only happens on one virtual machine (the production machine, of course).

I boiled it down to the following simple example.
The client looks like this:
```
@MqttSubscriber
@Slf4j
public class MySubscriber {

    @Topic("${client.readtopic}")
    public void receive(byte[] data) {
        String message = new String(data);
        log.info(message);
    }
}
```
Its built into a docker container named mqtt-test which is used in the following docker compose file:

```
version: "3.7"

services:

  client:
    image: mqtt-test:1.0.0
    restart: always
    networks:
      - consumer
    environment:
      - MQTT_CLIENT_SERVER-URI=tcp://mqtt:1883
      - MQTT_CLIENT_CLIENT-ID=test
      - CLIENT_READTOPIC=/in/test
    depends_on:
      - mqtt

  mqtt:
    image: "hivemq/hivemq-ce:2020.5"
    restart: always
    ports:
      - 1883:1883
    networks:
      - consumer

networks:
  consumer:
```

When I'm running this docker compose file on my production machine then the client is not able to connect to the mqtt broker.
During startup the client throws the following error and exists:
```
12:54:19.485 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.mqtt.v3.intercept.MqttSubscriberAdvice]

Message: Timed out waiting for a response from the server
Path Taken: new MqttSubscriberAdvice(BeanContext beanContext,MqttBinderRegistry binderRegistry,MqttSubscriberExceptionHandler exceptionHandler,[MqttAsyncClient mqttAsyncClient])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.mqtt.v3.intercept.MqttSubscriberAdvice]

Message: Timed out waiting for a response from the server
Path Taken: new MqttSubscriberAdvice(BeanContext beanContext,MqttBinderRegistry binderRegistry,MqttSubscriberExceptionHandler exceptionHandler,[MqttAsyncClient mqttAsyncClient])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1925)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2679)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2665)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2337)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2311)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1245)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
	at io.micronaut.mqtt.v3.intercept.$MqttSubscriberAdviceDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3022)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2897)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:772)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:759)
	at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$32(DefaultBeanContext.java:1596)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1595)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2812)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at de.test.Application.main(Application.java:11)
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Timed out waiting for a response from the server
	at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
	at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
	at io.micronaut.mqtt.v3.client.MqttClientFactory.mqttClient(MqttClientFactory.java:50)
	at io.micronaut.mqtt.v3.client.$MqttClientFactory$MqttClient0Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	... 23 common frames omitted

```

This message appears in the broker logs:
```
Client ID: UNKNOWN, IP: UNKNOWN disconnected ungracefully.
```

At the same time other (non-micronaut) mqtt clients are able to connect to the server.
When I'm running the same setup on my local machine it works.
When I'm running it on another VM it works.

I tried several things on the prod machine:
Using another MQTT server has no effect. The error message stays the same.
Switching the Micronaut versions between 2.2.x and 2.3.x has no effect.
Switching between mqtt v3 and v5 has no effect.
I changed several client settings like timeouts and so on without any effect (besides waiting longer for the error to appear).

I replaced my client class from above with something where I create the paho mqtt client myself and this works:
```
@Slf4j
@Singleton
public class MySubscriber {

    @Property(name="mqtt.client.server")
    String server;

    @Property(name="mqtt.client.port")
    int port;

    @Property(name="client.readtopic")
    String topic;

    @Property(name="mqtt.client.client-id")
    String identifier;

    MqttAsyncClient client;

    public void connect() throws MqttException {
        client = new MqttAsyncClient("tcp://"+ server + ":" + port, identifier);
        client.connect().waitForCompletion(10000);
    }

    @EventListener
    @Async
    public void loadConferenceData(final ServerStartupEvent event) {
        try {
            final MqttProperties props = new MqttProperties();
            props.setSubscriptionIdentifiers(Arrays.asList(new Integer[] { 0 }));
            connect();
            client.subscribe(new MqttSubscription[] { new MqttSubscription(topic, 0) }, null,
                    null, (actualTopic, message) -> System.out.println(message), props);
        } catch (MqttException e) {
            e.printStackTrace();
        }
    }

}
```
So it seems there is something in the way the client is created by micronaut that prevents the client from subscribing successfully to the mqtt broker.
Has anyone any idea what that could be?

**Comment by graemerocher** [comment]
Your environment variables look incorrect with dashes instead of underscores `MQTT_CLIENT_SERVER-URI`

**Comment by sebplorenz** [comment]
The environment variables are working.

But I found out that creating the mqtt client with an executorService in the MQTTClientFactory causes the connection problem.
In the MQTTClientFactory the mqtt client is created this way:
```
MqttAsyncClient client = new MqttAsyncClient(configuration.getServerUri(), configuration.getClientId(), clientPersistence, new TimerPingSender(consumerExecutor), consumerExecutor);
```
If it is done without the executorService like this:
```
MqttAsyncClient client = new MqttAsyncClient(configuration.getServerUri(), configuration.getClientId(), clientPersistence, new TimerPingSender(), null);
```
then it works.
Maybe this is related to https://github.com/eclipse/paho.mqtt.java/issues/638
It seems that the paho client has problems with using external executor services under some circumstances described in that bug.

**Comment by sebplorenz** [comment]
OK, I just found out that our little production VM was set to one core. With two or more cores the Micronaut MQTT subscriber works just fine.

You can reproduce the bug by starting an mqtt subscriber with VM args -XX:ActiveProcessorCount=1

Maybe a warning/error should be added stating that with only one available core the Micronaut MQTT client is not gonna work.

**Comment by graemerocher** [comment]
Yeah seems like a documentation issue, would make a nice contribution if you added a note to the docs
